# 项目相关配置
ruoyi:
  # 名称
  name: 管理系统
  # 版本
  version: 3.8.7
  # 版权年份
  copyrightYear: 2024
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/ruoyi/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8089
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.horzits: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 主库数据源
      master:
        #driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/liyuhuan?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: 20031021zlz
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭 //krhx.f3322.net:58123/amgw
        enabled: true
        #driverClassName: ru.yandex.clickhouse.ClickHouseDriver
        url: jdbc:clickhouse://192.168.10.95:8123/amgw
        username: default
        password: 123123
      # 农业平台业务库
      business:
        # 从数据源开关/默认关闭
        enabled: true
        url: jdbc:mysql://192.168.10.97:3306/amgw?serverTimezone=UTC&noAccessToProcedureBodies=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: root
        password: 123456
      # 蔬菜停车业务库
      parksc:
        # 从数据源开关/默认关闭
        enabled: true
        url: jdbc:mysql://192.168.10.97:3306/parksc?serverTimezone=UTC&noAccessToProcedureBodies=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: root
        password: 123456
      # 水果停车业务库
      parksg:
        # 从数据源开关/默认关闭
        enabled: true
        url: jdbc:mysql://192.168.10.97:3306/parknm?serverTimezone=UTC&noAccessToProcedureBodies=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: root
        password: 123456
      # 数据中台业务库
      datastation:
        # 从数据源开关/默认关闭
        enabled: true
        url: jdbc:mysql://192.168.10.70:3306/datastation?serverTimezone=UTC&noAccessToProcedureBodies=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: root
        password: 123456
      # 数据湖中间库数据源
      searchs:
        enabled: true
        url: jdbc:mysql://192.168.10.95:3306/syncamgw?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
        username: root
        password: 111111
      # zsl数据源
      zsl:
        enabled: true
        url: jdbc:mysql://192.168.10.97:3306/zsl?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: 123456
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置连接超时时间
      connectTimeout: 30000
      # 配置网络超时时间
      socketTimeout: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      #validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: ruoyi
        login-password: 123456
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  #main:
   # lazy-initialization: true
# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# MyBatis
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.horzits.**.domain,com.horzits.business.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  # configLocation: classpath:mybatis/mybatis-config.xml
  configuration:
    # 自动驼峰命名规则（camel case）映射
    # 如果您的数据库命名符合规则无需使用 @TableField 注解指定数据库字段名
    mapUnderscoreToCamelCase: true
    # 默认枚举处理类,如果配置了该属性,枚举将统一使用指定处理器进行处理
    # org.apache.ibatis.type.EnumTypeHandler : 存储枚举的名称
    # org.apache.ibatis.type.EnumOrdinalTypeHandler : 存储枚举的索引
    # com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler : 枚举类需要实现IEnum接口或字段标记@EnumValue注解.
    ##defaultEnumTypeHandler: org.apache.ibatis.type.EnumTypeHandler
    # 当设置为 true 的时候，懒加载的对象可能被任何懒属性全部加载，否则，每个属性都按需加载。需要和 lazyLoadingEnabled 一起使用。
    ##aggressiveLazyLoading: true
    # MyBatis 自动映射策略
    # NONE：不启用自动映射
    # PARTIAL：只对非嵌套的 resultMap 进行自动映射
    # FULL：对所有的 resultMap 都进行自动映射
    ##autoMappingBehavior: PARTIAL
    # MyBatis 自动映射时未知列或未知属性处理策手机
    # NONE：不做任何处理 (默认值)
    # WARNING：以日志的形式打印相关警告信息
    # FAILING：当作映射失败处理，并抛出异常和详细信息
    ##autoMappingUnknownColumnBehavior: NONE
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 开发环境开启日志打印
    #log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl  # 生产环境关闭日志打印
    cache-enabled: false
  global-config:
    # 是否打印 Logo banner
    banner: true
    # 是否初始化 SqlRunner
    enableSqlRunner: false
    dbConfig:
      # 主键类型
      # AUTO 数据库ID自增
      # NONE 空
      # INPUT 用户输入ID
      # ASSIGN_ID 全局唯一ID
      # ASSIGN_UUID 全局唯一ID UUID
      # idType: ASSIGN_UUID
      idType: ASSIGN_ID
      # 表名前缀
      #tablePrefix: null
      # 字段 format,例: %s,(对主键无效)
      #columnFormat: null
      # 表名是否使用驼峰转下划线命名,只对表名生效
      tableUnderline: true
      # 大写命名,对表名和字段名均生效
      #capitalMode: false


# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*
minidao :
  base-package: org.jeecg.modules.jmreport.desreport.dao*
  db-type: mysql
# 报表配置
jeecg:
#  minidao-datasource:
#
#    jdbc-url: jdbc:mysql://127.0.0.1:3306/ruoyi387?autoReconnect=true&failOverReadOnly=false&maxReconnects=1000&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
#    username: root
#    password: 123456
#
#    driver-class-name: com.mysql.cj.jdbc.Driver

  jmreport:
    #多租户模式，默认值为空(created:按照创建人隔离、tenant:按照租户隔离) (v1.6.2+ 新增)
    saasMode:
    # 平台上线安全配置
    firewall:
      # 数据源安全 (开启后，不允许使用平台数据源、SQL解析加签并且不允许查询数据库) true/false
      dataSourceSafe: false
      # 低代码开发模式（dev:开发模式，prod:发布模式—关闭在线报表设计功能，分配角色admin、lowdeveloper可放开限制）
      lowCodeMode: dev
    #自定义项目前缀
    customPrePath:
    #预览分页自定义
    pageSize:

      - 10
      - 20
      - 30
      - 40
    #打印纸张自定义
    printPaper:
      - title: A4纸
        size:
          - 210
          - 297
      - title: A3纸
        size:
          - 297
          - 420
      - title: A2纸
        size:
          - 420
          - 594
    #接口超时设置（毫秒）
    connect-timeout: 300000
#农业平台md5秘钥
amgw:
  am_pw_des_key_user_acc: apoidsfupaoidfdd

